# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# workflow 名称
name: 部署基于 koa 的 node 后端服务

# 触发 workflow 的条件
on:
  push:
    branches: [action]

# workflow 执行的任务
jobs:
  build:
    # 指定运行的虚拟机环境
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 指定 node 镜像
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 使用官方 action 获取源码
      - uses: actions/checkout@v3

      # 使用 Node 镜像
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # 运行打包编译脚本
      # - name: Install project dependencies
      - run: yarn install --prod --registry=https://registry.npmmirror.com

      # - name: Build with yarn
      - run: yarn run build

      - name: Delpoy files to server and restart node service
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          user: ${{ secrets.ALIYUN_USER }}
          key: ${{ secrets.ALIYUN_KEY }}
          first_ssh: |
            ls -al
          scp: |
            ./dist => /root/projects/koa_service
            ./package.json => /root/projects/koa_service
          last_ssh: |
            export NVS_HOME="$HOME/.nvs"
            [ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh"
            node -v
            cd /root/projects/koa_service
